### ISSUE TITLE
undercloud deployment fails with openstack plugin: rabbitmq-server does not start (hosts problem?)

### ISSUE THREAD

**Issue by voyageur** [redhat-openstack/infrared#286]
Running infrared stable branch, rdo-cloud as backend, with these infrared steps:
```
infrared openstack --cloud rdo-cloud --image CentOS-7-x86_64-GenericCloud-1703 --user centos --key-file ~/.ssh/id_rsa --prefix ir- --topology-nodes 'undercloud:1,controller:1,compute:1'
infrared tripleo-undercloud --version ocata --images-task import  --images-url https://images.rdoproject.org/ocata/rdo_trunk/current-tripleo/stable
```

rabbitmq-server does not start properly when installing the undercloud, it cannot connect to epmd on localhost:
```
May 16 16:30:35 ir-undercloud-0.redhat.local rabbitmqctl[21513]: attempted to contact: ['rabbit@ir-undercloud-0']
May 16 16:30:35 ir-undercloud-0.redhat.local rabbitmqctl[21513]: rabbit@ir-undercloud-0:
May 16 16:30:35 ir-undercloud-0.redhat.local rabbitmqctl[21513]: * unable to connect to epmd (port 4369) on ir-undercloud-0: timeout (timed out)
May 16 16:30:35 ir-undercloud-0.redhat.local rabbitmqctl[21513]: current node details:
May 16 16:30:35 ir-undercloud-0.redhat.local rabbitmqctl[21513]: - node name: 'rabbitmq-cli-63@ir-undercloud-0'
May 16 16:30:35 ir-undercloud-0.redhat.local rabbitmqctl[21513]: - home dir: /var/lib/rabbitmq
May 16 16:30:35 ir-undercloud-0.redhat.local rabbitmqctl[21513]: - cookie hash: JL78t0bh5gO9OkTKkf7KRg==
May 16 16:30:35 ir-undercloud-0.redhat.local systemd[1]: Failed to start RabbitMQ broker.
```
Initial hosts file has only localhost entries:
```
127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
::1         localhost localhost.localdomain localhost6 localhost6.localdomain6
```
The "Update hosts user" step in plugins/tripleo-undercloud/create_user.yml adds this line in /etc/hosts:
`38.145.32.172    ir-undercloud-0.redhat.local ir-undercloud-0`

While after installing openstack packages there will also be this line:
`127.0.0.1 ir-undercloud-0.novalocal ir-undercloud-0`

Removing the "Update hosts user" will allow the creation of the undercloud to go through, but then the playbook ends with:
```
PLAY [localhost] *************************************************************************************************************************************************************
                 [[ previous play time: 0:32:23.419035 = 1943.42s / 2579.33s ]]
Traceback (most recent call last):
  File "/home/bcafarel/Work/infrared/.venv/bin/infrared", line 10, in <module>
    sys.exit(main())
  File "/home/bcafarel/Work/infrared/.venv/lib/python2.7/site-packages/infrared/main.py", line 357, in main
    return specs_manager.run_specs(args) or 0
  File "/home/bcafarel/Work/infrared/.venv/lib/python2.7/site-packages/infrared/api.py", line 176, in run_specs
    self.parser, args=args)
  File "/home/bcafarel/Work/infrared/.venv/lib/python2.7/site-packages/infrared/api.py", line 150, in spec_handler
    ansible_args=control_args.get('ansible-args', None))
  File "/home/bcafarel/Work/infrared/.venv/lib/python2.7/site-packages/infrared/core/execute.py", line 38, in ansible_playbook
    vars_dict=extra_vars or {})
  File "/home/bcafarel/Work/infrared/.venv/lib/python2.7/site-packages/infrared/core/execute.py", line 72, in _run_playbook
    return cli.run()
  File "/home/bcafarel/Work/infrared/.venv/lib/python2.7/site-packages/ansible/cli/playbook.py", line 154, in run
    results = pbex.run()
  File "/home/bcafarel/Work/infrared/.venv/lib/python2.7/site-packages/ansible/executor/playbook_executor.py", line 125, in run
    all_vars = self._variable_manager.get_vars(loader=self._loader, play=play)
  File "/home/bcafarel/Work/infrared/.venv/lib/python2.7/site-packages/ansible/vars/__init__.py", line 236, in get_vars
    include_delegate_to=include_delegate_to,
  File "/home/bcafarel/Work/infrared/.venv/lib/python2.7/site-packages/ansible/vars/__init__.py", line 424, in _get_magic_variables
    variables['ansible_play_hosts_all'] = [x.name for x in self._inventory.get_hosts(pattern=play.hosts or 'all', ignore_restrictions=True)]
AttributeError: 'NoneType' object has no attribute 'name'
```
Not sure if the fix is correct, so opening an issue (note: switching the 2 lines order seems to do the trick too, at least for rabbitmq-server restart command)

**Comment by voyageur** [comment]
Tested fixed in 79d27e8b1a0cd70c16cb4d0dce0c54ebad35e408. Now to check the next steps!
