### ISSUE TITLE
 infrared tripleo-undercloud --version 13 --images-task=rpm --build z13

### ISSUE THREAD

**Issue by NileshChandelkar** [redhat-openstack/infrared#402]
While deploying Openstack version 13/16 faced the issue below:

~~~
 [WARNING]: Found both group and host with same name: hypervisor

ERROR   <class 'ansible.errors.AnsibleParserError'>: no action detected in task. This often indicates a misspelled module name, or incorrect module path.

The error appears to have been in '/root/.infrared/plugins/tripleo-undercloud/backup.yml': line 23, column 13, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


          - name: Use sha256 to calculate checksum
            ^ here

Traceback (most recent call last):
  File "/root/.venv_infrared/bin/infrared", line 8, in <module>
    sys.exit(main())
  File "/root/.venv_infrared/lib/python2.7/site-packages/infrared/main.py", line 541, in main
    return specs_manager.run_specs(args) or 0
  File "/root/.venv_infrared/lib/python2.7/site-packages/infrared/api.py", line 209, in run_specs
    self.parser, args=args)
  File "/root/.venv_infrared/lib/python2.7/site-packages/infrared/api.py", line 171, in spec_handler
    ansible_args=control_args.get('ansible-args', None))
  File "/root/.venv_infrared/lib/python2.7/site-packages/infrared/core/execute.py", line 160, in ansible_playbook
    ir_workspace=ir_workspace, ir_plugin=ir_plugin)
  File "/root/.venv_infrared/lib/python2.7/site-packages/infrared/core/execute.py", line 297, in _run_playbook
    raise error
ansible.errors.AnsibleParserError: no action detected in task. This often indicates a misspelled module name, or incorrect module path.

The error appears to have been in '/root/.infrared/plugins/tripleo-undercloud/backup.yml': line 23, column 13, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


          - name: Use sha256 to calculate checksum
            ^ here
~~~

~~~
(.venv_infrared) [root@smicro-s1029p-04 infrared]# cat /etc/*release
NAME="Red Hat Enterprise Linux Server"
VERSION="7.9 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.9"
PRETTY_NAME="Employee SKU"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.9:GA:server"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.9
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.9"
Red Hat Enterprise Linux Server release 7.9 (Maipo)
Red Hat Enterprise Linux Server release 7.9 (Maipo)
(.venv_infrared) [root@smicro-s1029p-04 infrared]# 
~~~

**Comment by NileshChandelkar** [comment]
Can we git attention to this issue please, Same has been observed for RHOSP16

**Comment by NileshChandelkar** [comment]
* Commented this section below section in **/root/.infrared/plugins/tripleo-undercloud/backup.yml**

~~~
#          - name: Use sha256 to calculate checksum
#            ansible.builtin.stat:
#                path: "{{ undercloud_image_file }}"
#                checksum_algorithm: sha256
#                get_checksum: yes
#            register: local_sha256sum
~~~

* Deployment is running now

**Comment by fhubik** [comment]
Afaik this problem is not seen anywhere in our pipeline, likely caused by Ansible version mismatch (https://stackoverflow.com/questions/47159193/why-does-ansible-show-error-no-action-detected-in-task-error).

I suggest to check whether venv is properly created (https://github.com/redhat-openstack/infrared/blob/master/requirements.txt) or possibly different interpreter env is used (ansible.cfg/interpreter_python) env-wide or per task/playbook...

**Comment by sanjaychari** [comment]
I faced the same issue. Instead of commenting the code snippet that caused the issue as suggested here, I followed the solution from https://github.com/redhat-openstack/infrared/issues/408, and changed ansible.builtin.stat to stat. I was able to workaround this issue with that solution.

**Comment by knoha-rh** [comment]
To fix this issue, the change needs to be merged. https://review.gerrithub.io/c/redhat-openstack/infrared/+/520276
